### ISSUE TITLE
Error regenerating results from supplementary material

### ISSUE THREAD

**Issue by pressureless** [enjmiah/SketchConnectivity#1]
Many `.vec files` failed when running the following script to regenerate the results from supplementary material

```python3 tools/run_batch.py data/inputs_train+validate.yml```

<img width="650" alt="image" src="https://github.com/enjmiah/SketchConnectivity/assets/8511053/d3fec6c7-751e-4086-a9eb-a7de3444537d">

**Comment by enjmiah** [comment]
Hello,

You can use `run_pipeline.py` on the individual file to see what the issue is:

    python tools/run_pipeline.py "data/bcloud/LMA test__6.vec" --root . --tmpdir tmp

It seems like the version of pybind11 we used has some bug(?) relating to overload resolution on Python 3.8 and 3.9 (and won't even compile on later versions):

```
Traceback (most recent call last):
  File "C:\...\SketchConnectivity\tools\run_pipeline.py", line 418, in <module>
    main()
  File "C:\...\SketchConnectivity\tools\run_pipeline.py", line 400, in main
    _s.save_pdf(graph_v7, entry['v7_annotations_conn_all'],
TypeError: save_pdf(): incompatible function arguments. The following argument types are supported:
    1. (graph: sketching::StrokeGraph, path: str, params: _sketching.PlotParams, predictions: List[sketching::ClassifierPrediction] = [], face_colors: numpy.ndarray[numpy.int32[m, 1]] = array([], dtype=int32), highlighted_faces: List[int] = []) -> None
    2. (stroke: sketching::Stroke, path: str, params: _sketching.PlotParams, pred_info: sketching::StrokeSnapInfo = None) -> None
    3. (d: sketching::Drawing, path: str, params: _sketching.PlotParams) -> None

Invoked with: StrokeGraph(
  Vertex 0: { p: (904.11, 541.555),  he: 543 }
  ...
), 'tmp\\LMA test__6_v7_annotations_conn_all.pdf', <_sketching.PlotParams object at 0x00000248D99965B0>; kwargs: predictions=[]
```

However, it works with Python 3.7.16.

**Comment by pressureless** [comment]
Thank you for the response! I have successfully built the project on my Mac. You're right, I need to update pybind11 when compiling. (`Python 3.11 + gurobi11.0.0_macos_universal2.pkg + pybind11 v2.10.1`)

The problem seems to be the timeout threshold, maybe my Mac is too slow. It takes almost one hour for some files.

**Comment by pressureless** [comment]
It crashed for some input.
<img width="860" alt="image" src="https://github.com/enjmiah/SketchConnectivity/assets/8511053/5237f8a1-e415-4004-83a2-2c48cdca9f81">
<img width="982" alt="image" src="https://github.com/enjmiah/SketchConnectivity/assets/8511053/3f8ef9e8-c20c-492d-a171-0b2c5772f895">
